name: Rust

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/chechout@v3
      - uses: dtolnay/rust-toolchain@stable
        with: 
          components: rustfmt 
      - name: Enforce formatting
        run: cd rust && cargo fmt --check